In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

if you have confuse what model should i used for my problem in above imported model to classify hand written digit
cross validation will help you in selection

In [15]:
digit=load_digits()
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(digit.data,digit.target,test_size=0.3)

use above model and find score for each

In [16]:
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9685185185185186

In [17]:
sm=SVC()
sm.fit(x_train,y_train)
sm.score(x_test,y_test)

0.987037037037037

In [18]:
rf=RandomForestClassifier(n_estimators=40)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9592592592592593

run above model every time different score so its not good sample change 
used k fold cross valdiation
split data set in k fold then one used for test and rem for train then change and son on 


In [20]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [21]:
for train_index,test_index in kf.split([0,1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)


[4 5 6 7 8 9] [0 1 2 3]
[0 1 2 3 7 8 9] [4 5 6]
[0 1 2 3 4 5 6] [7 8 9]


above first used for test 0,1,2,3 and renmin two for train and so on

In [23]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [36]:
from sklearn.model_selection import StratifiedKFold #same kfold separte each category
skf=StratifiedKFold(n_splits=3)

three array store score of above three model

In [39]:
score_log=[]
score_svc=[]
score_rf=[]
for train_index,test_index in kf.split(digit.data):
    x_train,x_test,y_train,y_test=digit.data[train_index],digit.data[test_index],\
                                   digit.target[train_index],digit.target[test_index]
    score_log.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    score_svc.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    score_rf.append(get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))

C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stab

In [40]:
score_log

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [41]:
score_svc

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [42]:
score_rf

[0.9398998330550918, 0.9549248747913188, 0.9232053422370617]

above for loop and finc core can we do with cross_val_score 

In [72]:
from sklearn.model_selection import cross_val_score
sco=cross_val_score(LogisticRegression(max_iter=100),digit.data,digit.target,cv=skf)



C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stab

In [73]:
print(f"logistic regression  score {sco},  mean {np.mean(sco)}")

logistic regression  score [0.92153589 0.94156928 0.91652755],  mean 0.9265442404006677


In [77]:
scoe=cross_val_score(SVC(),digit.data,digit.target,cv=kf)
print(f"SVC  score {scoe},  mean {np.mean(scoe)}")

SVC  score [0.96661102 0.98163606 0.95492487],  mean 0.9677239844184752


In [76]:
score_rf=cross_val_score(RandomForestClassifier(n_estimators=40),digit.data,digit.target,cv=kf)
print(f"Random forest score {score_rf},  mean {np.mean(score_rf)}")

Random forest score [0.94323873 0.94991653 0.93155259],  mean 0.941569282136895


svc has high mean value used svc model for digit classifaction