head tail p=1/2
queen card=4/52=1/13

total diamond =13
queen=1     p(Queen/Daimond)=1/13   daimond already  occure 
is called conditional prob
p(A/B)=P(B/A)*P(A) / P(B)



In [1]:
import pandas as pd 
df=pd.read_csv('tested.csv')
df.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [2]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

Survived  Pclass     Sex   Age     Fare
0         0       3    male  34.5   7.8292
1         1       3  female  47.0   7.0000
2         0       2    male  62.0   9.6875
3         0       3    male  27.0   8.6625
4         1       3  female  22.0  12.2875

In [3]:
target=df.Survived
inputs=df.drop(['Survived'],axis='columns')


In [4]:
dumies=pd.get_dummies(inputs.Sex)
dumies.head()

female   male
0   False   True
1    True  False
2   False   True
3   False   True
4    True  False

In [5]:
inputs=pd.concat([inputs,dumies],axis='columns')
inputs.head(2)

Pclass     Sex   Age    Fare  female   male
0       3    male  34.5  7.8292   False   True
1       3  female  47.0  7.0000    True  False

In [6]:
inputs.drop(["Sex"],axis="columns",inplace=True)
inputs.head(3)

Pclass   Age    Fare  female   male
0       3  34.5  7.8292   False   True
1       3  47.0  7.0000    True  False
2       2  62.0  9.6875   False   True

In [7]:
inputs.columns[inputs.isna().any()]

Index(['Age', 'Fare'], dtype='object')

In [8]:
inputs.Age=inputs.Age.fillna(inputs.Age.mean())
inputs.Fare=inputs.Fare.fillna(inputs.Fare.mean())

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(inputs,target,test_size=0.2)


In [10]:
len(x_train)

334

In [11]:
len(x_test)

84

In [12]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

In [13]:
model.fit(x_train,y_train)

GaussianNB()

In [14]:
model.score(x_test,y_test)

1.0

In [15]:
y_test[:10]

282    1
330    1
151    0
193    0
59     1
171    0
11     0
61     0
251    0
351    0
Name: Survived, dtype: int64

In [16]:
model.predict(x_test[:10])

array([1, 1, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64)

In [17]:
model.predict_proba(x_test[:10])

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [18]:
x_test

Pclass       Age      Fare  female   male
282       3  30.27259    7.7500    True  False
330       2  48.00000   36.7500    True  False
151       3  30.27259    7.8958   False   True
193       2  61.00000   12.3500   False   True
59        1  36.00000  262.3750    True  False
..      ...       ...       ...     ...    ...
340       2  18.00000   10.5000   False   True
195       3  33.00000    7.8542   False   True
315       3  17.00000    7.7333    True  False
128       2  42.00000   13.0000   False   True
240       1  55.00000   27.7208    True  False

[84 rows x 5 columns]

In [19]:
import numpy as np
x=np.array([[2,46,34.89,0,1]])

In [20]:
model.predict(x)

C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


array([0], dtype=int64)